In [ ]:
#use 3.12.7
import pandas as pd
import plotly.express as px
import numpy as np
from scipy import stats
file1= open("WKS WORK TO INCOME TABLE.csv", "r")
df = pd.read_table("WKS WORK TO INCOME TABLE.csv", sep='\\,', engine='python')
df.rename(columns={'"INCWAGE"': 'INCWAGE', '"WKSWORK1"': 'WKSWORK'}, inplace=True)
df.sort_values('INCWAGE', ascending=False, inplace=True)
df1= df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]
fig=px.scatter(df1,x='WKSWORK', y='INCWAGE', title="Correlation of Weeks Worked to Income", trendline="ols", trendline_color_override="blue",color_discrete_sequence=['green'])
fig.update_layout(xaxis_title="Weeks Worked (Previous Year)", yaxis_title="Pre-Tax Salary & Wage Income")
df1

       "AGE"  "EDUC"  WKSWORK  "WKSWORK2"  INCWAGE
18451     44     125       50           6   288000
18489     42     125       50           6   288000
40071     44     124       52           6   288000
39993     38     124       52           6   288000
43803     44     123       52           6   287000
...      ...     ...      ...         ...      ...
43796     61     111        0           0        0
43797     40      81       52           6        0
71146     34      40        0           0        0
43798     63      92        0           0        0
0         52      73        0           0        0

[84845 rows x 5 columns]

In [2]:
df1.corr()

               "AGE"    "EDUC"   WKSWORK  "WKSWORK2"   INCWAGE
"AGE"       1.000000  0.067234  0.007409    0.014656  0.110981
"EDUC"      0.067234  1.000000  0.207901    0.208302  0.397184
WKSWORK     0.007409  0.207901  1.000000    0.994321  0.564042
"WKSWORK2"  0.014656  0.208302  0.994321    1.000000  0.567162
INCWAGE     0.110981  0.397184  0.564042    0.567162  1.000000

In [3]:
df1.describe()

              "AGE"        "EDUC"       WKSWORK    "WKSWORK2"        INCWAGE
count  84845.000000  84845.000000  84845.000000  84845.000000   84845.000000
mean      41.418893     88.924274     37.107113      4.206093   44082.041464
std       13.535453     22.737605     22.069990      2.560664   47979.682176
min       18.000000     20.000000      0.000000      0.000000       0.000000
25%       30.000000     73.000000     12.000000      1.000000       0.000000
50%       41.000000     81.000000     52.000000      6.000000   34000.000000
75%       53.000000    111.000000     52.000000      6.000000   65000.000000
max       65.000000    125.000000     52.000000      6.000000  288000.000000

In [4]:
fig